#!/usr/bin/env python

Import("env")
Import("env_modules")

env_fluid_simulation = env_modules.Clone()

# Godot source files
env_fluid_simulation.add_source_files(env.modules_sources, "*.cpp")
if env.editor_build:
    env_fluid_simulation.add_source_files(env.modules_sources, "editor/*.cpp")
